### ISSUE TITLE
Update URL for gay.com

### ISSUE THREAD

**Issue by starfys** [TheTorProject/ooniprobe-android#106]
As of 03 August 2017, `gay.com` has changed ownership. It appears that the website no longer has an HTTPS version, just an HTTP connection that redirects to `https://vanguardnow.org/`

This causes a problem in the "Web Connectivity" test, which expects "https://gay.com" to resolve correctly.

Relevant line:
https://github.com/TheTorProject/ooniprobe-android/blob/8550eda6b036879fc86d0e42a0ac81e5738fd3fb/app/src/main/res/raw/global.txt#L527

More information:
This was tested and verified by performing
```bash
# Checks open ports
nmap gay.com
# Checks HTTPS
curl -v https://gay.com
```
from 3 locations:
* Home internet
* School internet (MTSU)
* DigitalOcean droplet (NYC)

On all 3 locations, port 443 does not show as open, and performing `curl` fails to connect using HTTPS

**Comment by hellais** [comment]
Thanks for the detailed report! We will look into it.

**Comment by lorenzoPrimi** [comment]
@hellais can this be closed/moved?

**Comment by starfys** [comment]
The URL seems to be updated  in [app/src/main/assets/test_lists/global.csv](https://github.com/TheTorProject/ooniprobe-android/blob/5c86913c50e4b84592b8efb032dbc4e1ee73045a/app/src/main/assets/test_lists/global.csv#L584) but not [app/src/main/res/raw/global.txt](https://github.com/TheTorProject/ooniprobe-android/blob/8550eda6b036879fc86d0e42a0ac81e5738fd3fb/app/src/main/res/raw/global.txt#L527)

**Comment by lorenzoPrimi** [comment]
That file is not present anymore since three versions.
The new file is this one https://github.com/TheTorProject/ooniprobe-android/blob/master/app/src/main/assets/test_lists/global.csv

**Comment by starfys** [comment]
In that case, I'll go ahead and close this.
