### ISSUE TITLE
Allow periodic measurements

### ISSUE THREAD

**Issue by willscott** [TheTorProject/ooniprobe-android#11]
It would be great to have a way to schedule measurements to run periodically, rather than only when explicitly run by the user.

**Comment by bassosimone** [comment]
I agree. I am not sure whether this was planned in the original plan for the App. I also see some complexity in that, meaning that one should get right a number of things, e.g., adding options to enable this behavior, whether to run tests where using 3G/4G, maximum data quota. That's way, perhaps, I'd focus on this functionality after we have a fully functional release of the App doing all OONI user initiated staff. Does it make sense?

cc: @hellais @lorenzoPrimi

**Comment by willscott** [comment]
yes. this seems like a subsequent thing and not part of the minimum viable product / first release.

**Comment by lorenzoPrimi** [comment]
I guess we can close this issue as now it is supported
