### ISSUE TITLE
Improve the user interface of the network Android client

### ISSUE THREAD

**Issue by lorenzoPrimi** [TheTorProject/ooniprobe-android#19]
I am opening this ticket to show what is the current implementation of the user interface for the ooniprobe Android and discuss potential improvements to the user interface before dedicated tickets for each improvement is created.

Here are screenshots for each of the views.
### Step 1 - Introduction

![screenshot_20161112-131950](https://cloud.githubusercontent.com/assets/1616097/20237740/122e79b6-a8db-11e6-9279-d18973b567ee.png)
### Step 2 - Risks

![screenshot_20161112-131955](https://cloud.githubusercontent.com/assets/1616097/20237747/2345cc7c-a8db-11e6-8dce-a1305776e5b5.png)
### Step 3 - Quiz
![screenshot_20161004-101041](https://cloud.githubusercontent.com/assets/1616097/20237655/4ea64efc-a8d9-11e6-9cf7-411f9730a6aa.png)
![screenshot_20161112-132000](https://cloud.githubusercontent.com/assets/1616097/20237751/31cc44d8-a8db-11e6-821f-4e8fda65ecdc.png)
![screenshot_20161112-132007](https://cloud.githubusercontent.com/assets/1616097/20237752/31d10e3c-a8db-11e6-8d40-a3523a450c0d.png)

### Step 4 - Configuration

![screenshot_20161112-132010](https://cloud.githubusercontent.com/assets/1616097/20237755/372353fe-a8db-11e6-9bd6-013472d04c94.png)
## Settings

![screenshot_20161112-130201](https://cloud.githubusercontent.com/assets/1616097/20237671/c9f3d9da-a8d9-11e6-9a07-44094b0b6b4b.png)
### Select a test

![screenshot_20161112-130218](https://cloud.githubusercontent.com/assets/1616097/20237669/c035d4d4-a8d9-11e6-8e76-0dfa51546ea7.png)
## Running tests

![screenshot_20161112-132026](https://cloud.githubusercontent.com/assets/1616097/20237756/3d7c5b10-a8db-11e6-9602-9e647c153d73.png)
## Finished tests

![screenshot_20161112-130204](https://cloud.githubusercontent.com/assets/1616097/20237699/474ca024-a8da-11e6-9d80-2c1a0a13e314.png)

## Delete test

![screenshot_20161112-130247](https://cloud.githubusercontent.com/assets/1616097/20237682/fe288340-a8d9-11e6-8d8e-80ca65a509ce.png)
### Click on measurement with many inputs

![screenshot_20161112-130256](https://cloud.githubusercontent.com/assets/1616097/20237674/e2d5e934-a8d9-11e6-8ae2-32d3f896004d.png)
### Measurement - Web connectivity

![screenshot_20161112-130301](https://cloud.githubusercontent.com/assets/1616097/20237675/e3a82156-a8d9-11e6-8d00-51a1395e6d68.png)

**Comment by lorenzoPrimi** [comment]
Here is how the app looks now.

## First start wizard
### Step 1 - Introduction

![screenshot_20161202-101536](https://cloud.githubusercontent.com/assets/1616097/20830270/1677a2fe-b880-11e6-914b-8d0364c74ccf.png)
### Step 2 - Risks

![screenshot_20161202-101541](https://cloud.githubusercontent.com/assets/1616097/20830268/10367faa-b880-11e6-8f2f-09aff5e993b6.png)
### Step 3 - Quiz

![screenshot_20161202-101547](https://cloud.githubusercontent.com/assets/1616097/20830285/24149624-b880-11e6-9f1f-dbccad13a407.png)
### Step 4 - Configuration

![screenshot_20161202-101551](https://cloud.githubusercontent.com/assets/1616097/20830292/2a2c007e-b880-11e6-92c6-4f6751d4b34b.png)
### Done

![screenshot_20161202-101556](https://cloud.githubusercontent.com/assets/1616097/20830297/2f1d45d4-b880-11e6-80d7-3041312b5973.png)
## Settings

![screenshot_20161202-101603](https://cloud.githubusercontent.com/assets/1616097/20830301/335f1f0a-b880-11e6-9faa-157300bdf815.png)
## Running tests

![screenshot_20161202-101832](https://cloud.githubusercontent.com/assets/1616097/20830307/39bf5824-b880-11e6-9e13-884416af3af9.png)
## Finished tests

![screenshot_20161202-101918](https://cloud.githubusercontent.com/assets/1616097/20830312/4206d16a-b880-11e6-8c2a-567f21c97a2e.png)
## Delete test

![screenshot_20161202-101940](https://cloud.githubusercontent.com/assets/1616097/20830351/69f58e46-b880-11e6-8a2b-d16369fbee78.png)
### Click on measurement with many inputs

![screenshot_20161202-101929](https://cloud.githubusercontent.com/assets/1616097/20830322/4d2d0a00-b880-11e6-8119-78195f015e6c.png)
### Measurement - Web Connectivity

![screenshot_20161202-101935](https://cloud.githubusercontent.com/assets/1616097/20830329/53c9ca1a-b880-11e6-8b31-2023fe2e5f26.png)
### Info - Web Connectivity

![screenshot_20161202-101923](https://cloud.githubusercontent.com/assets/1616097/20830335/58528e1e-b880-11e6-92f3-c32362d632b9.png)

**Comment by darkk** [comment]
I've noticed some minor glitches in `v0.1.0-rc` UI:
- [ ] I'm unsure that OONI works to **fight** network censorship. Homepage says *detecting censorship*, *monitoring censorship*... (summons @agrabeli and @hellais )
- [ ] *Web connectivity* pop-up has some signs of leaked markdown near text *"**HTTP status codes don't match"*, preformatted text is not preformatted in the popup as well
- [ ] that's `v0.1.0-rc`, but it claims to be `1.0` in *App info* and does not mention version somewhere in-the-app
- [ ] the app is named `ooniprobe`, but every single app I have installed is named with first letter being capital (`Maps`, `OsmAnd+`, `FBReader`, etc.). `ooniprobe` stands out a bit.
- [ ] *Collector address* edit field is empty when I tap to edit it, IMHO it should be populated with current collector
- [ ] description text of `HTTP Invalid request line` is truncated
- [ ] `RUN` button goes mad in landscape format, but truncated text is still not visible

![screenshot_2016-12-12-13-32-30](https://cloud.githubusercontent.com/assets/21046/21096793/bb6500b6-c07a-11e6-8c1c-55d93c3a0020.png)

Let's paint the bikeshed #E83B52 :-)

**Comment by lorenzoPrimi** [comment]
- The text is copied from ooniprobe web version, so better address this point to the people you tagged
- I don't see them, do you have a screenshot? (it's an issue of https://github.com/TheTorProject/ooni-wui/ )
- The version in the app store will be 1.0 these are all pre releases
- I noticed it and we discussed on IRC, everybody agreeed with ooniprobe lowercase
- Good one, will do soon
- Screenshot? I see it correctly
- Never thought of landscape, I have all phones locked in portrait only ;) But will solve it soon!

**Comment by bassosimone** [comment]
@lorenzoPrimi, it's not clear to me whether we can keep this open or we can close

**Comment by lorenzoPrimi** [comment]
Waiting for @darkk comment
