### ISSUE TITLE
Test reminder is not triggered at the default time

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooniprobe-android#28]
### Description
Test reminder is not respecting the (default) time set for notifications.

### Steps to Reproduce
Enable the option `Run test reminder` with (default) Time `18:00`. 

**Expected behavior:** 
Test reminder notification sent at desired (set) time.

**Actual behavior:**
Test reminder notifications sent every 15 minutes.

**Comment by lorenzoPrimi** [comment]
solved in https://github.com/measurement-kit/ooniprobe-android/commit/f75d5501318947611f5df740934cc7e6f7df4a30
