### ISSUE TITLE
UI: empty screen in "Past Tests" on init

### ISSUE THREAD

**Issue by darkk** [TheTorProject/ooniprobe-android#35]
UI screen is empty right after app v0.1.0-rc.3 install.
That's expected, but empty state [may be improved](https://material.io/guidelines/patterns/empty-states.html) per material design guidelines. :-)

![empty_screen](https://cloud.githubusercontent.com/assets/21046/22496438/305fdd4a-e863-11e6-9f10-0ac4b01dddd5.jpeg)

**Comment by lorenzoPrimi** [comment]
Will be implemented in a future version.
Hint for iOS: use this component : https://github.com/dzenbot/DZNEmptyDataSet

**Comment by lorenzoPrimi** [comment]
Called EmptyRecyclerView on Android
https://github.com/sismics/docs/blob/master/docs-android/app/src/main/java/com/sismics/docs/ui/view/EmptyRecyclerView.java

**Comment by hellais** [comment]
I am thinking something along the lines of this:

![screen shot 2017-02-14 at 17 12 31 0000](https://cloud.githubusercontent.com/assets/424620/22940167/e9d87442-f2d8-11e6-97e7-cd3f48b876bc.png)

If we like this then I can make you an asset of the image of the octopus in greyscale.

cc @ebdet2002

**Comment by lorenzoPrimi** [comment]
I like it, I don't know if in iOS I can "jump" from this screen to run tests screen, in case I can't I'll remove the button.
You can procede making the asset, thanks!

**Comment by ebdet2002** [comment]
This looks fine for a zero state!

**Comment by hellais** [comment]
This is implemented.
