### ISSUE TITLE
Missing back button on test result page

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooniprobe-android#37]
In the test result page the back button is missing.

![screen shot 2017-02-05 at 00 56 28 0000](https://cloud.githubusercontent.com/assets/424620/22622830/1161e5ea-eb3e-11e6-8dd7-705af273f402.png)

Edit: the back button is also missing when I am on the pages containing descriptions of tests.

**Comment by lorenzoPrimi** [comment]
In android the back button doesn't exist.
It's in the keyboard

**Comment by hellais** [comment]
> In android the back button doesn't exist.
> It's in the keyboard

But some apps, even google ones, do have the back button when you are inside of a nested view. Example from gmail (the yellow circled):

![navigation_up_vs_back_gmail](https://cloud.githubusercontent.com/assets/424620/22647423/424c5560-ec69-11e6-9cd9-41570dfe81b1.png)
