### ISSUE TITLE
Test reminder/scheduler issues

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-android#41]
1. it seems confusing that you set a timer and said timer expires "around" that time: for example, I set a test for 9:40 PM and it started at 9:30 PM (and same happened today as said on IRC)

2. apparently, powering off and on again the device loses memory about the fact that tests were scheduled at a fixed time, which does not appear to be the desired behaviour.

**Comment by lorenzoPrimi** [comment]
Solved 2.
Don't have idea about 1. my tests start at the desired time, can you check again?

**Comment by hellais** [comment]
Can we close this?

Is there something to do to test for 2) or should we close it and if the bug re-appears we re-open it?

**Comment by bassosimone** [comment]
@hellais I guess I need to check this again with the latest version of the app.
