### ISSUE TITLE
Green dot indicating completed test missing

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-android#42]
I guess this is already known and possibly already being worked on. Nonetheless, lest we forget, I am leaving here this issue documenting that the green dot is missing (using the code in #33 updated to the following commit 6afbc8a197fee plus local changes to use v0.4.0-beta.3).

**Comment by lorenzoPrimi** [comment]
Fixed on menu and past test list, still not working on the hamburger menu due to low API support
