### ISSUE TITLE
Test info add back button

### ISSUE THREAD

**Issue by lorenzoPrimi** [TheTorProject/ooniprobe-android#43]
In the test info screen we need a back button, for the moment the menu button is enabled also in this screen

**Comment by Lymphatus** [comment]
This is valid for also for Settings and About. Also, in any of these screens, if you press the back button the application quits instead of going back to the previous screen/default screen.

**Comment by lorenzoPrimi** [comment]
@Lymphatus the fact that it quits when you are in the MainAcrtivity it is the normal behaviour of an Android app

**Comment by Lymphatus** [comment]
Open the app -> go to Settings -> do whatever you want -> press back button. The application now quits. Is that expected? Shouldn't go back to the test screen?

**Comment by hellais** [comment]
This is done.
