### ISSUE TITLE
Failed/Incomplete NDT Speed Test view is displaying Loading

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooniprobe-android#48]
Failed or incomplete NDT Speed Test reports are displaying the text `Loading` instead of the actual report file.

![ndt-test-ooniprobe](https://cloud.githubusercontent.com/assets/4969544/22752255/84d17770-ee40-11e6-908f-8ae7fe6f4ef0.png)

**Comment by hellais** [comment]
Probably related: https://github.com/TheTorProject/ooniprobe-ios/issues/72

**Comment by hellais** [comment]
Does anybody have a sample of a JSON report that is triggering this error? 

I believe https://github.com/TheTorProject/ooni-wui/pull/29 should fix it, but I would like to test it.

**Comment by anadahz** [comment]
> Does anybody have a sample of a JSON report that is triggering this error?

```
    "annotations": {
        "platform": "android"
    },
    "data_format_version": "0.2.0",
    "input": "",
    "measurement_start_time": "2017-02-14 18:10:01",
    "probe_asn": "ASXXX",
    "probe_cc": "DE",
    "probe_ip": "127.0.0.1",
    "report_id": "20170214T181001Z_ASXXX_qzcUOXDQt0g6xBZb3H7BjNec58gy0lTwBclht8DTr4t3aTUnGU",
    "software_name": "ooniprobe-android",
    "software_version": "1.1.2",
    "test_keys": {
        "advanced": null,
        "client_resolver": "xxx.xxx.xxx.xxx",
        "failure": "unknown_failure 8018",
        "server_address": "ndt.iupui.mlab1.ham01.measurement-lab.org",
        "server_port": 3001,
        "server_version": "v4.0.0.1-Web100",
        "simple": null,
        "summary_data": {},
        "test_c2s": [],
        "test_s2c": [
            null
        ],
        "test_suite": 54
    },
    "test_name": "ndt",
    "test_runtime": 7.95145893096924,
    "test_start_time": "2017-02-14 18:09:59",
    "test_version": "0.1.0"
}
```

**Comment by hellais** [comment]
Ok so I have tested it with the JSON report given by @anadahz and it now properly shows an error message when it fails to render the view.

See:

![screen shot 2017-02-15 at 14 04 49 0000](https://cloud.githubusercontent.com/assets/424620/22977748/e1f289f2-f387-11e6-8aef-87340cff73ba.png)

Is there some better text I should be using for this?

Note: the second line is the actual exception that triggers the render so it can be more or less anything. For the time being I am not adding specific logic in the web UI to handle faulty NDT measurements as I think this should probably be written in a standard way in the actual measurement file and not put too much logic for figuring out why and how the report failed to parse.

**Comment by hellais** [comment]
Edit: Actually I now see that there is in fact an failure value that I can use to render a better error message and I will use that.

![screen shot 2017-02-15 at 14 13 45 0000](https://cloud.githubusercontent.com/assets/424620/22978087/2580bd14-f389-11e6-997b-9ef0a0158fe0.png)


Nonetheless if for any reason the webUI fails to render the result page because of unhandled exceptions, we will now instead of being stuck in the loading screen, show the above better error page.

**Comment by hellais** [comment]
This is fixed.
