### ISSUE TITLE
Greeting (Get started) view not properly aligned

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooniprobe-android#49]
```
$ getprop ro.build.version.release
4.1.1

$ getprop ro.build.version.sdk
16

$ dumpsys window |grep Display
Display: init=768x1024 cur=768x1024 app=768x976 rng=768x720-1024x976
```

The greeting (Get started) view is not properly alligned.
![get-started-ooniprobe](https://cloud.githubusercontent.com/assets/4969544/22752374/f13f441e-ee40-11e6-8726-b47aa024851e.png)

**Comment by lorenzoPrimi** [comment]
@anadahz can you check if it's fixed in app version 1.1.2?

**Comment by anadahz** [comment]
@lorenzoPrimi Could you please upload (no App store on this device) the app version `1.1.2` so that I could test it ?

**Comment by lorenzoPrimi** [comment]
@bassosimone will comment here when it will be released

**Comment by lorenzoPrimi** [comment]
@anadahz will now tell us if this version solves the problem

**Comment by anadahz** [comment]
ooniprobe version 1.1.2

![ooniprobe-st](https://cloud.githubusercontent.com/assets/4969544/22941449/2098583e-f2ee-11e6-8781-f5c1523b3c9b.png)

**Comment by hellais** [comment]
What should be done about this?

**Comment by lorenzoPrimi** [comment]
Never had the ability to reproduce it, neither with an emulator with the same specifications.

**Comment by anadahz** [comment]
Label: Further testing required

**Comment by anadahz** [comment]
I can further reproduce this, please let me know if you need anything specific to help you debug this issue.

**Comment by bassosimone** [comment]
I also don't have a device with these specifications. I will try and see whether I can reproduce this bug with an emulator with same specifications, but I honestly don't see why this should be the case.

I guess that we arm a timer. If neither @lorenzoPrimi nor I can reproduce and @anadahz is not able to implement a fix for this within, say, two weeks, we close the bug as wontfix.

**Comment by anadahz** [comment]
Makes sense we can close this issue.
Emulators are quite helpful but they "just" try hard to emulate a "real" environment.
I can bring the device with me next time we meet so that we can further investigate this issue.

**Comment by bassosimone** [comment]
I actually found a way to replicate the bug: Nexus S, API 13, armeabi emulator.

See screenshot below:

![screen shot 2017-05-04 at 15 04 20](https://cloud.githubusercontent.com/assets/337298/25704808/429f60b4-30db-11e7-9567-d5d525b661f5.png)

**Comment by lorenzoPrimi** [comment]
There is no reason why the image should be aligned left, this is the XML for displaying it:
`
<ImageView
            android:id="@+id/test_logo"

            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_centerVertical="true"
            android:src="@drawable/ic_ooni_sparkles"
            android:scaleType="fitEnd"
            android:layout_centerHorizontal="true"
            android:adjustViewBounds="true" />
`

Can you try to adjust some of them and retry running it?

**Comment by bassosimone** [comment]
Yeah, sure, I can look into it. Since @anadahz report was about API 16, I believe this is still relevant.

I am starting to suspect that this has to do with the total size of the screen, not the API.
