### ISSUE TITLE
Expose app version number in app

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooniprobe-android#52]
It should be possible from inside the app to check what is the version of the currently installed app.

**Comment by lorenzoPrimi** [comment]
Only the app version or also mk version?

**Comment by hellais** [comment]
Ideally it would show the app version and the MK version.

**Comment by lorenzoPrimi** [comment]
@bassosimone is there an API to check the current mk version or should I hardcode it?

**Comment by bassosimone** [comment]
See https://github.com/measurement-kit/measurement-kit/blob/master/include/measurement_kit/common/version.h: I suggest to use the `mk_version` function. (It may not be exported on Android, in such case I'll do that)

**Comment by lorenzoPrimi** [comment]
Ok, so regarding to this issue, we have to decide where to expose the app and mk version, my proposals are
* Left menu
* Settings screen
* About screen

My preference is putting it into the about screen because is the most appropriate and most "empty".
If nobody has objections I'll start this task.

**Comment by hellais** [comment]
@ebdet2002 where do you think it would be most appropriate to place the version number of the app? In the settings page or the about page?

**Comment by ebdet2002** [comment]
I've seen it in both places. I personally prefer about because that's where
I'm used to looking, but it seems that convention is now to nest it in
settings. I think the logic for the latter is that it's easier to 1click
copy to clipboard if it's a clickable field in settings, which could be
useful for error reporting.

I'll leave this decision up to you.

**Comment by lorenzoPrimi** [comment]
Added in about screen. Waiting for your feedback on the strings
![screenshot_1487186319](https://cloud.githubusercontent.com/assets/1616097/22991303/18b95b08-f3bc-11e6-89b9-26162cee4bfe.png)

**Comment by hellais** [comment]
This is done.
