### ISSUE TITLE
Compile everything from scratch for f-droid

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-android#54]
The pre-requisite is to have a Linux system with NDK installed. We have been compiling for Android using macOS for quite some time now (my Ubuntu box died ten months ago).

Anyway (this is a *ghetto* procedure to have it compiled, we will make the process more smooth with also the use case of f-droid in mind in subsequent releases):

# clone the repositories
- git clone --branch stable https://github.com/measurement-kit/measurement-kit
- git clone --branch release/v0.4.0 https://github.com/measurement-kit/android-libs
- git clone --branch f-droid https://github.com/TheTorProject/ooniprobe-android

# cross compile dependencies
- cd measurement-kit
- ./build/android/dependency *path-to-ndk-dir* geoip
- ./build/android/dependency *path-to-ndk-dir* libressl
- ./build/android/dependency *path-to-ndk-dir* libevent
- ./build/android/archive-deps  # ignore gpg error [1]
- sign generated archive with your pgp key

# cross compile measurement-kit
- cd ../android-libs
- cp ../measurement-kit/*archive* .
- cp ../measurement-kit/*archive*.asc .
- *make sure that the Makefile mentions exactly the same archive name* [2]
- make dist NDK_BUILD=*path-to-ndk-build*  # ignore pgp error [1]
- sign the generated archive with your pgp key

# move MK and dependencies into app
- cd ../ooniprobe-android
- cp ../android-libs/*archive* .  # not the dependencies the measurement_kit named archive
- cp ../android-libs/*archive*.asc .
- *make sure the Makefile mentions exactly the same archive name* [2]
- make unpack
- gradle build  # I think

[1] I hope you are not able to sign things on my behalf using my pgp key :)
[2] if the name is correct, the Makefile does not download it

**Comment by anadahz** [comment]
Thanks @bassosimone.
While cross compiling dependencies with `android-ndk-r13b-linux-x86_64`:
```
Cross-compiling libevent for all archs

Cross compiling libevent for arch armeabi
Creating toolchain for API 9 and ARCH arm in /home/user/build-measurement-kit/measurement-kit/build/android/toolchain/armeabi

Cross compiling for armeabi
/root/build-measurement-kit/measurement-kit/build/android/cross: 111: export: armv5te-none-linux-androideabi: bad variable name
```

**Comment by bassosimone** [comment]
Wait: does it mean that you compile `geoip` and `libressl` but not `libevent`?

**Comment by anadahz** [comment]
I wasn't able to compile either `geoip` neither `libressl` or `libevent`.

**Comment by bassosimone** [comment]
@anadahz In theory the script is written for any shell. In practice in most cases it has been run using bash. I am against making bash only scripts, that's way there's no `#!/bin/bash` at the beginning but it is possible that I've used some bashism without noticing it. Since you're root (why?) on a system, and I guess you're on Debian, probably the shell you're using is dash.

So, things that I'd try:

- [ ] try to execute using `bash`, just for `geoip`, which is the fastest build
- [ ] try to wrap with double quotes the exports at line 111 and 112 and see whether it improves the situation (it seems to me there is a issue with the variable containing spaces there)

**Comment by anadahz** [comment]
@bassosimone It's a test server (that's why root is being used) but using bash on shell, changing the script (`sed -i '1 s,/bin/sh,/bin/bash,' measurement-kit/build/android/cross`) to run in bash seems to fix the issue with variables:
`# echo $SHELL`
`/bin/bash`
`# ./build/android/dependency ~/build-measurement-kit/android-ndk-r13b geoip`

```
Cross-compiling geoip for all archs

Cross compiling geoip for arch armeabi
Creating toolchain for API 9 and ARCH arm in /root/build-measurement-kit/measurement-kit/build/android/toolchain/armeabi

Cross compiling for armeabi

* step: configure

* step: make
- make 
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by bassosimone** [comment]
mmm, this does not look like the expected output. Can we take a step back and try to compile the geoip dependency without cross compiling? Could you do the following:

- [ ] wipe the repository (`git clean -dffx`)
- [ ] do a plain recompile of geoip (`./build/dependency geoip`)

To this end, it would be nice to make sure you have some basic dependencies installed such that you can cross compile: autoconf, automake, clang, g++, git, libtool, wget, curl. I guess that is all, but, if you see that some packages are missing, just install them :-).

Also, what Debian version are you using? I guess we need something with *at least* gcc >= 4.9.

**Comment by anadahz** [comment]
`Debian 8 (Jessie)`
`gcc (Debian 4.9.2-10) 4.9.2`

plain recompile (.`/build/dependency`) of `geoip`, `libressl`, `libevent` is successful.

**Comment by bassosimone** [comment]
Sweet! Now we need to figure out why cross compiling fails. To start off, I'd try and see whether wiping the repository as explained above and then `./build/android/dependency geoip` still fails or whether wiping it does the trick. Forcing bash should also help. I also feel like it would be good to fix places where scripts are compatible with dash. Basically, you should probably try to understand whether, for some reason, using dash causes the directory being wrong (in addition, of course, to the variables error already discussed above). Can you try?

**Comment by bassosimone** [comment]
@anadahz, have you made progresses? Could you update us? Or is there any blocker I could provide any help with?

**Comment by anadahz** [comment]
Right, now I'm able to cross compile measurement-kit and its dependencies. ;)

Some notes while building measurement-kit and dependencies:
- wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip # XXX: Find a package
- ./build/android/archive-deps # (sed  -i 's/7733D95B/YOUR_GPG_KEY/' build/android/archive-deps)
- make dist NDK_BUILD=path-to-ndk-build # (sed -i 's/738877AA6C829F26A431C5F480B691277733D95B/YOUR_GPG_KEY/' android-libs/Makefile

#### Required steps for Debian Jessie
```
apt -y install dh-autoreconf gnupg2 swig git-core && \
echo "deb http://httpredir.debian.org/debian testing main" > /etc/apt/sources.list.d/testing.list && \
echo -e "Package: *\nPin: release a=stable\nPin-Priority: 700\n\nPackage: /(gradle|android-sdk)/\nPin: release a=testing\nPin-Priority: 600" > /etc/apt/preferences.d/testing && \
apt update && apt -y install -t testing gradle android-sdk
```

##### grandle build
```
export ANDROID_HOME=/usr/lib/android-sdk && \
mkdir -p "$ANDROID_HOME/licenses" && \
echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license" && \
echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license" && gradle build 
```

<details><summary>grandle lint error</summary>

```
Incremental java compilation is an incubating feature.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2511Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72511Library UP-TO-DATE
:app:prepareComAndroidSupportRecyclerviewV72511Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCompat2511Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCoreUi2511Library UP-TO-DATE
:app:prepareComAndroidSupportSupportCoreUtils2511Library UP-TO-DATE
:app:prepareComAndroidSupportSupportFragment2511Library UP-TO-DATE
:app:prepareComAndroidSupportSupportMediaCompat2511Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42511Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2511Library UP-TO-DATE
:app:prepareComGithubAndroidDeveloperLBAutoFitTextView4Library UP-TO-DATE
:app:prepareMePanavtecWizard12Library UP-TO-DATE
:app:prepareUkCoChrisjenxCalligraphy220Library UP-TO-DATE
:app:prepareUsFerasMdvMarkdownview110Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugJavaWithJavac UP-TO-DATE
:app:compileDebugNdk UP-TO-DATE
:app:compileDebugSources UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:transformClassesWithDexForDebug UP-TO-DATE
:app:mergeDebugJniLibFolders UP-TO-DATE
:app:processDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
:app:validateSigningDebug
:app:packageDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:checkReleaseManifest
:app:prepareReleaseDependencies
:app:compileReleaseAidl UP-TO-DATE
:app:compileReleaseRenderscript UP-TO-DATE
:app:generateReleaseBuildConfig UP-TO-DATE
:app:generateReleaseResValues UP-TO-DATE
:app:generateReleaseResources UP-TO-DATE
:app:mergeReleaseResources UP-TO-DATE
:app:processReleaseManifest UP-TO-DATE
:app:processReleaseResources UP-TO-DATE
:app:generateReleaseSources UP-TO-DATE
:app:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:app:compileReleaseJavaWithJavac UP-TO-DATE
:app:compileReleaseNdk UP-TO-DATE
:app:compileReleaseSources UP-TO-DATE
:app:lintVitalRelease
:app:mergeReleaseShaders UP-TO-DATE
:app:compileReleaseShaders UP-TO-DATE
:app:generateReleaseAssets UP-TO-DATE
:app:mergeReleaseAssets UP-TO-DATE
:app:transformClassesWithDexForRelease UP-TO-DATE
:app:mergeReleaseJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:app:processReleaseJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:app:packageRelease UP-TO-DATE
:app:assembleRelease
:app:assemble
:app:lint
Ran lint on variant release: 85 issues found
Ran lint on variant debug: 85 issues found
Wrote HTML report to file:///root/ooniprobe-android/app/build/outputs/lint-results-debug.html
Wrote XML report to file:///root/ooniprobe-android/app/build/outputs/lint-results-debug.xml
:app:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
</details>

Any ideas on how to resolve the lint errors?

**Comment by eighthave** [comment]
I highly recommend heeding lint errors, they are almost always correct.  Looking at lint warnings is worthwhile too.   We have even set some warnings to fail the build when they arise.

**Comment by bassosimone** [comment]
xref: https://gitlab.com/fdroid/rfp/issues/31

**Comment by bassosimone** [comment]
@anadahz thank you for your effort! I guess it should be not complex to modify the build process to use another *PGP* key if the correct environment variable is specified.

As I commented in fdroid/rfp, I think it would make sense to invest time to make MK cross compilable using the ndk-build or perhaps directly cmake. I wonder how complex is to automate the dependencies, which use the GNU build system (but perhaps we can either tap into existing cmake if they also have one for Windows and/or write one for them).

Apart from that, I'd really like to know if using another shell creates issues (I am not a fan of scripts that only work with bash and I'd really like to fix portability issues :-).

**Comment by bassosimone** [comment]
I have implemented and merged support for AAR in https://github.com/measurement-kit/android-libs/pull/29. By end of week, I'll also finish off #82 such that we can use jcenter and we don't need to run a custom script to package the app. I guess the other requirement, apart from using jcenter, would be to avoid non-free dependencies, is this correct @eighthave?

**Comment by bassosimone** [comment]
(The status of this issue is basically "done" in the sense that no further action needs to be taken and we can close this as soon as we have confirmation about further f-droid steps, if any.)

**Comment by eighthave** [comment]
sounds like you have it sorted out.

**Comment by bassosimone** [comment]
Okay, I'm going to close this issue and follow up on [fdroid/rfp](https://gitlab.com/fdroid/rfp/issues/31).
