### ISSUE TITLE
Toasts notifications lasts for too long

### ISSUE THREAD

**Issue by Lymphatus** [TheTorProject/ooniprobe-android#58]
Once a test is done, the Toast Notifications lasts indefinitely/for a very long time. Even if you visit the past tests screen right after a test is completed, the notification is not cleared. Moreover, if you completely exit the application, the notification is not killed and tapping on it does not clear it.

![screenshot_1486819261](https://cloud.githubusercontent.com/assets/12133996/22854083/07d55e08-f066-11e6-9a2b-44b1968f3c1a.png)

**Comment by hellais** [comment]
@lorenzoPrimi is this done?

**Comment by lorenzoPrimi** [comment]
Yes
