### ISSUE TITLE
Android app "local reference table overflow" crash

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-android#60]
Migrated from: https://github.com/measurement-kit/measurement-kit/issues/1125

Diagnosis: I noticed that, commenting out the following code:

```Java
.on_entry(new org.openobservatory.measurement_kit.nettests.EntryCallback() {
    @Override
    public void callback(String entry) {
        setAnomaly(entry, currentTest);
    }
})
```

made the crash disappear. As such, I am inclined to think that the issue lies in the Java side (or perhaps is *implied* by the currently used design, but still the fix must be done here).

**Comment by lorenzoPrimi** [comment]
I can suggest to modify that line in 
`if (currentTest.anomaly < 2) setAnomaly(entry, currentTest);
`
but I can't guarantee it will solve it

**Comment by bassosimone** [comment]
Uhm, actually the issue was in Java code; see https://github.com/measurement-kit/android-libs/pull/26. This should now be fixed, so closing the issue.
