### ISSUE TITLE
Add support for Farsi (text displayed from right to left)

### ISSUE THREAD

**Issue by agrabeli** [TheTorProject/ooniprobe-android#65]
Elections in Iran are approaching (April 2017) and it would be good to have translated the app to Farsi in advance. However, a prerequisite is adding support for Farsi so that text can be displayed from right to left.

**Comment by lorenzoPrimi** [comment]
In progress on https://github.com/TheTorProject/ooniprobe-android/tree/release/1.1.4

**Comment by lorenzoPrimi** [comment]
But we don't have any farsi translation on transifex

**Comment by bassosimone** [comment]
This has been implemented, right, @lorenzoPrimi?
