### ISSUE TITLE
Add mobile deep linking support

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooniprobe-android#66]
This was a request from a user.

The basic idea is that I want to invite people to test the reachability of my site say `http://example.com`. When a certain site I want to embed on this page a button that the user can click on and it will:

1. If the app is installed open the app and run the specified test against the url `http://example.com`/ (by first showing confirmation that the specified test is about to run on that site).

2. If the app is not installed redirect me to the market so I can install the app

I believe this can be done by registering a custom schema in the app.

See: http://stackoverflow.com/questions/3469908/make-a-link-in-the-android-browser-start-up-my-app

Edit: It seems like this thing has a name: [Mobile Deep Linking](https://en.wikipedia.org/wiki/Mobile_deep_linking)

**Comment by lorenzoPrimi** [comment]
Under development in https://github.com/TheTorProject/ooniprobe-android/tree/feature/URI_scheme

**Comment by hellais** [comment]
I created a specification for this here: https://github.com/TheTorProject/ooniprobe-ios/pull/117
