### ISSUE TITLE
Changing color used to indicate anomalies?

### ISSUE THREAD

**Issue by bassosimone** [TheTorProject/ooniprobe-android#67]
I was discussing with a user that submitted a long and informative bug report and he/she was commenting that red is, in his/her opinion, too aggressive for what we consider anomalies, as red is usually used to indicate very-bad-things. He maintains that perhaps yellow or pink would better convey the meaning of "look closely at this". I think this makes sense.

xref: https://github.com/TheTorProject/ooniprobe-ios/issues/97

**Comment by lorenzoPrimi** [comment]
@bassosimone I guess this can be closed

**Comment by bassosimone** [comment]
Is the new app using a different set of colors?

**Comment by lorenzoPrimi** [comment]
An anomaly has never been red. If with anomaly you consider the test failed.
Red = Blocking
Yellow = Test failed
Blue = Test Ok

**Comment by bassosimone** [comment]
So, the user request was indeed to avoid "red" for blocking because actually we're not 100% sure and it was suggested to use a slightly less hard colour. This bug was reported by a very knowledgeable user who was able to see that it was indeed a false positive. I am also fine to close this as wontfix but would like to make sure that we're aware of the bug that was reported.

(I _thought_ anomaly meant red and yellow was called failed.)

**Comment by lorenzoPrimi** [comment]
We don't use a full red anymore but #e03131
I don't think the color is such a big issue as we use the work "blocked", that website is blocked according to our test
@elioqoshi

**Comment by bassosimone** [comment]
@lorenzoPrimi I think this is more a problem of middlebox tests than of web_connectivity.

**Comment by lorenzoPrimi** [comment]
Middlebox doesn't use red at all. Only orange and green. I guess can be closed

**Comment by lorenzoPrimi** [comment]
![group 1243](https://user-images.githubusercontent.com/1616097/37903809-971bc5fa-30f9-11e8-9441-98d7f225352c.png)

**Comment by bassosimone** [comment]
Excellent, glad that we can also close this :-)

Thanks for prodding me to review the past issues
