### ISSUE TITLE
Unpopulated placeholders

### ISSUE THREAD

**Issue by noplanman** [TheTorProject/ooniprobe-android#90]
I noticed that some link placeholders aren't populated properly, see the screenshot below.

Using a Fairphone 2 with Android 5.1. As I'm not very familiar with reporting bugs for mobile devices, is there any extra info you need?

![ooniprobe-placeholders](https://cloud.githubusercontent.com/assets/9423417/26439233/8ab99322-4127-11e7-82e1-29f045b353c7.jpg)

**Comment by hellais** [comment]
I believe this issue is solved by https://github.com/TheTorProject/ooni-wui/commit/ed4557ec3c761fec852d8931c0a442fcb25ba6db.

@noplanman what version of the app are you running?

**Comment by noplanman** [comment]
@hellais I'm on 1.1.3 (latest version available on F-Droid)

When 1.1.4 is available, I'll install that and see if it's fixed, thanks!

**Comment by lorenzoPrimi** [comment]
@noplanman 1.1.5 is out, is this still an issue?

**Comment by noplanman** [comment]
Perfectly working now :+1:

Nice work!
